name: "Setup CI"

description: "Set up Java, sbt and cache for CI"

inputs:
  java-version:
    description: "The Java version to use"
    default: "21"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      name: Set up JDK
      with:
        distribution: "temurin"
        java-version: "${{ inputs.java-version }}"
        cache: "sbt"
    - uses: sbt/setup-sbt@v1
